services:
  frontend:
    build:
      context: .
      dockerfile: web-front/Dockerfile
    ports:
      - '4200:80'
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: api/Dockerfile
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: production
