services:
  postgres:
    image: postgres:15
    container_name: dev-postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: rosa_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
